var firstName = "Ese";
var lastName = "Gbenmo";
var middleName = "Divine";
console.log("your name is: " + firstName + " " + lastName + " " + middleName);
var firstNumber = 20;
var secondNumber = 30;
var thirdNumber = 50;
console.log(result = firstNumber + secondNumber + thirdNumber);
console.log(result);
alert(result);
var StateOfBeing = prompt("How are you doing");
console.log(StateOfBeing);
var favoriteColor = "Blue";
var favoriteFood = "Pizza";
var favoriteHobby = "Coding";
console.log("Your favorites are: Color - " + favoriteColor + ", Food - " + favoriteFood + ", Hobby - " + favoriteHobby);
var numberOne = 10;
var numberTwo = 25;
var numberThree = 40;
var sum = numberOne + numberTwo + numberThree;
console.log("The sum of the numbers is: " + sum);
alert("The sum is: " + sum);
var age = prompt("What is your age?");
console.log("Your age is: " + age);
var city = "Lagos";
var country = "Nigeria";
var continent = "Africa";
console.log("Location: " + city + ", " + country + ", " + continent);
var height = 175;
var weight = 70;
var bmi = (weight / (height * height)) * 10000;
console.log("Your BMI is: " + bmi.toFixed(2));
var favoriteMovie = "Inception";
var favoriteSong = "Imagine";
var favoriteBook = "1984";
console.log("Your favorites are: Movie - " + favoriteMovie + ", Song - " + favoriteSong + ", Book - " + favoriteBook);
var length = 5;
var width = 10;
var area = length * width;
console.log("The area of the rectangle is: " + area + " square units");
alert("The area is: " + area + " square units");
var favoriteSeason = prompt("What is your favorite season?");
console.log("Your favorite season is: " + favoriteSeason);
var currentYear = 2024;
var birthYear = 2000;
var age = currentYear - birthYear;
console.log("You are " + age + " years old");
var distance = 150; // in kilometers
var speed = 60; // in km/h
var time = distance / speed;
console.log("It will take " + time + " hours to travel " + distance + " kilometers at " + speed + " km/h");
alert("Travel time: " + time + " hours");
var petName = "Buddy";
var petType = "Dog";
var petAge = 5;
console.log("Your pet is a " + petType + " named " + petName + " and is " + petAge + " years old.");
var base = 10;
var height = 15;
var areaOfTriangle = 0.5 * base * height;
console.log("The area of the triangle is: " + areaOfTriangle);
alert("The area of the triangle is: " + areaOfTriangle);
var currentTemperature = 30;
var desiredTemperature = 22;
var temperatureDifference = currentTemperature - desiredTemperature;
console.log("The temperature needs to decrease by " + temperatureDifference + " degrees.");
alert("Decrease temperature by " + temperatureDifference + " degrees.");
var favoriteAnimal = prompt("What is your favorite animal?");
console.log("Your favorite animal is: " + favoriteAnimal);
var itemPrice = 250;
var taxRate = 0.08;
var totalPrice = itemPrice + (itemPrice * taxRate);
console.log("The total price including tax is: " + totalPrice);
alert("The total price is: " + totalPrice);
var hoursWorked = 40;
var hourlyRate = 15;
var weeklySalary = hoursWorked * hourlyRate;
console.log("Your weekly salary is: $" + weeklySalary);
alert("Your weekly salary is: $" + weeklySalary);
var userName = "John";
var userSurname = "Doe";
var userMiddleName = "Smith";
console.log("Full name: " + userName + " " + userMiddleName + " " + userSurname);
var lengthOfSquare = 7;
var areaOfSquare = lengthOfSquare * lengthOfSquare;
console.log("The area of the square is: " + areaOfSquare + " square units");
alert("Area of the square: " + areaOfSquare + " square units");
var currentSpeed = 80;
var speedLimit = 60;
var speedExcess = currentSpeed - speedLimit;
console.log("You are exceeding the speed limit by " + speedExcess + " km/h");
alert("Slow down! You are over the speed limit by " + speedExcess + " km/h");
var birthYear = prompt("Enter your birth year:");
var currentYear = new Date().getFullYear();
var userAge = currentYear - birthYear;
console.log("You are " + userAge + " years old.");
var favoriteFruit = "Apple";
var favoriteVegetable = "Carrot";
var favoriteDrink = "Coffee";
console.log("Your favorites are: Fruit - " + favoriteFruit + ", Vegetable - " + favoriteVegetable + ", Drink - " + favoriteDrink);
