let a = 6;
let b = 7;
console.log(a + b);
const c = 7;
const d = 8;
alert(c * d);
let e = 10;
let f = 5;
console.log(e - f); // Subtraction: 10 - 5 = 5
const g = 12;
const h = 4;
alert(g / h); // Division: 12 / 4 = 3
let i = 15;
let j = 3;
console.log(i % j); // Modulus (remainder): 15 % 3 = 0
const k = 8;
const l = 2;
alert(k ** l); // Exponentiation: 8^2 = 64
let m = 20;
let n = 5;
console.log(m * n); // Multiplication: 20 * 5 = 100
const o = 9;
const p = 3;
alert(o + p); // Addition: 9 + 3 = 12
let q = 25;
let r = 5;
console.log(q / r); // Division: 25 / 5 = 5
const s = 14;
const t = 7;
alert(s - t); // Subtraction: 14 - 7 = 7
let u = 16;
let v = 4;
console.log(u % v); // Modulus: 16 % 4 = 0
const w = 2;
const x = 3;
alert(w ** x); // Exponentiation: 2^3 = 8
let y = 6;
let z = 2;
console.log(y * z); // Multiplication: 6 * 2 = 12
const aa = 18;
const bb = 9;
alert(aa / bb); // Division: 18 / 9 = 2
let cc = 20;
let dd = 4;
console.log(cc - dd); // Subtraction: 20 - 4 = 16
const ee = 10;
const ff = 10;
alert(ee + ff); // Addition: 10 + 10 = 20
let gg = 7;
let hh = 2;
console.log(gg % hh); // Modulus: 7 % 2 = 1
const ii = 5;
const jj = 2;
alert(ii ** jj); // Exponentiation: 5^2 = 25
let kk = 9;
let ll = 3;
console.log(kk * ll); // Multiplication: 9 * 3 = 27
const mm = 21;
const nn = 7;
alert(mm / nn); // Division: 21 / 7 = 3
let oo = 30;
let pp = 10;
console.log(oo - pp); // Subtraction: 30 - 10 = 20
const qq = 4;
const rr = 4;
alert(qq + rr); // Addition: 4 + 4 = 8
